$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    responsive:{
        0:{
            items:1
        },
        350:{
            items:2
        },
        580:{
            items:3
        },
        900:{
            items:4
        },
        1200:{
            items:5
        }
    }
})